apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-script
data:
  set_redis_keys.sh: |
    #!/bin/bash
    REDIS_HOST="${REDIS_HOST}"
    REDIS_PORT="${REDIS_PORT}"
    REDIS_PASSWORD="${REDIS_PASSWORD}"

    KEY1="key1"
    VALUE1="value1"
    KEY2="key2"
    VALUE2="value2"
    KEY3="key3"
    VALUE3="value3"

    redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" <<-EOF
      SET "$KEY1" "$VALUE1"
      SET "$KEY2" "$VALUE2"
      SET "$KEY3" "$VALUE3"
    EOF