apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redis-container
            image: {{ .Values.redis.image }}
            command:
            - sh
            - -c
            - /bin/sh /scripts/set_redis_keys.sh
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            env:
            - name: REDIS_HOST
              value: "{{ .Values.redis.name }}-service.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.name }}-secret
                  key: redis-password
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: redis-script